config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('order/', include('order.urls', namespace='order')),
    path('product/', include('product.urls', namespace='product')),
    path('obtain-token/', obtain_jwt_token, name='obtain-token'),
    path('refresh-token/', refresh_jwt_token, name='refresh-token'),
    path('verify-token/', verify_jwt_token, name='verify-token'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CustomerRegisterView

app_name = 'customer'
urlpatterns = [
    path('login/', TemplateView.as_view(template_name='customer/login.html'),
         name='login'),
    path('register/', CustomerRegisterView.as_view(),
         name='register'),
]

order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PaymentComplete
from .views import CartExistCheckAPI
from .views import OrderListAPI
from .views import CartListAPI

app_name = 'order'
urlpatterns = [
    path('', TemplateView.as_view(template_name='order/order.html'),
         name='order-list'),
    path('cart/', TemplateView.as_view(template_name='order/cart.html'),
         name='cart'),
    path('cart-api/', CartListAPI.as_view(), name='cart-api'),
    path('order-api/', OrderListAPI.as_view(), name='order-api'),
    path('exist-api/', CartExistCheckAPI.as_view(), name='exist-api'),
    path('payments-complete/', PaymentComplete.as_view(),
         name='payments-complete'),
]

customer/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class CustomerManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('이메일이 필요')
        email = self.normalize_email(email)
        customer = self.model(email=email, **extra_fields)
        customer.set_password(password)
        customer.save(using=self._db)
        return customer

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)


class Customer(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='이메일', max_length=255, unique=True)
    # password = models.CharField(verbose_name='비밀번호', max_length=128)
    # level = models.CharField(verbose_name='등급', max_length=8,
    #                          choices=(('admin', 'admin'), ('user', 'user')))
    nickname = models.CharField(verbose_name='닉네임', max_length=255)
    register_date = models.DateTimeField(verbose_name='등록날짜',
                                         auto_now_add=True)
    shipping_address = models.TextField(verbose_name='배송주소')
    is_staff = models.BooleanField(verbose_name='직원계정', default=False)
    is_superuser = models.BooleanField(verbose_name='관리자계정', default=False)

    objects = CustomerManager()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    def __str__(self):
        return "<%d %s>" % (self.pk, self.email)

    class Meta:
        db_table = 'customer'
        verbose_name = '고객'
        verbose_name_plural = '고객'

customer/views.py
from django.shortcuts import render
from rest_framework import generics

from .serializer import RegisterSerializer


class CustomerRegisterView(generics.CreateAPIView):
    serializer_class = RegisterSerializer

    def get(self, request, *args, **kwargs):
        return render(request, template_name='customer/register.html')

templates/customer/login.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div id="login" class="container" style="padding: 50px 0px 30px 0px;">
    <div class="col-md-8 mx-auto">
        <br>
        <h3 class="text-center text-danger">로그인</h3><br>
        <div class="form-group">
            <label for="email" class="text-danger">이메일:</label><br>
            <input type="text" name="email" id="email" class="form-control" placeholder="이메일을 입력하세요">
        </div>
        <div class="form-group">
            <label for="password" class="text-danger">비밀번호:</label><br>
            <input type="password" name="password" id="password" class="form-control" placeholder="비밀번호를 입력하세요">
        </div>
        <div class="form-group">
            <div class="row">
                <input type="submit"
                       id="loginButton"
                       class="form-control btn btn-danger"
                       value="submit">
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <a href="{% url 'customer:register' %}"
                   class="form-control btn btn-secondary">Register here</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block ready %}
$('#loginButton').click(function() {
    $.post('/obtain-token/', {'email': $('#email').val(), 'password': $('#password').val()
    }).done(function(data) {
        saveToken(data);
        window.location = '/';
    }).fail(function(data) {
        alert("로그인에 실패했습니다.");
        console.log(data);
    });
});
{% endblock %}

templates/customer/register.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="container" style="padding: 50px 0px 30px 0px;">
    <div class="col-md-12 mx-auto">
        <h1 class="text-danger">회원가입</h1>
        <hr>
        <div class="form-group">
            <label for="InputEmail" class="text-danger">이메일 :</label>
            <input type="email" class="form-control" id="email" placeholder="이메일을 입력해주세요">
        </div>
        <div class="form-group">
            <label for="InputPassword" class="text-danger">비밀번호 :</label>
            <input type="password"
                   class="form-control"
                   id="password"
                   placeholder="비밀번호를 입력해주세요">
        </div>
        <div class="form-group">
            <label for="InputNickname" class="text-danger">닉네임 :</label>
            <input type="text" class="form-control" id="nickname" placeholder="닉네임을 입력해주세요">
        </div>
        <div class="form-group">
            <label for="InputShippingAddress" class="text-danger">주소 :</label>
            <input type="text" class="form-control" id="shipping_address" placeholder="주소를 입력해주세요">
        </div>
        <button class="form-control btn btn-danger" id="register">Register</button>
    </div>
</div>
{% endblock %}
{% block ready %}
registerCustomer();
{% endblock %}