config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('order/', include('order.urls', namespace='order')),
    path('product/', include('product.urls', namespace='product')),
    path('obtain-token/', obtain_jwt_token, name='obtain-token'),
    path('refresh-token/', refresh_jwt_token, name='refresh-token'),
    path('verify-token/', verify_jwt_token, name='verify-token'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PaymentComplete
from .views import CartExistCheckAPI
from .views import OrderListAPI
from .views import CartListAPI

app_name = 'order'
urlpatterns = [
    path('', TemplateView.as_view(template_name='order/order.html'),
         name='order-list'),
    path('cart/', TemplateView.as_view(template_name='order/cart.html'),
         name='cart'),
    path('cart-api/', CartListAPI.as_view(), name='cart-api'),
    path('order-api/', OrderListAPI.as_view(), name='order-api'),
    path('exist-api/', CartExistCheckAPI.as_view(), name='exist-api'),
    path('payments-complete/', PaymentComplete.as_view(),
         name='payments-complete'),
]

product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CategoryListAPI
from .views import ProductListAPI
from .views import ProductDetailAPI

app_name = 'product'
urlpatterns = [
    path('', TemplateView.as_view(template_name='product/product-list.html'),
         name='list'),
    path('<int:pk>/',
         TemplateView.as_view(template_name='product/product-detail.html'),
         name='detail'),
    path('list-api/', ProductListAPI.as_view(), name='list-api'),
    path('detail-api/<int:pk>/', ProductDetailAPI.as_view(),
         name='detail-api'),
    path('category-list-api/', CategoryListAPI.as_view(), name='category-api'),
]

product/models.py
from django.db import models

from customer.models import Customer


class Category(models.Model):
    name = models.CharField(verbose_name='카테고리', max_length=256, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        verbose_name = '카테고리'
        verbose_name_plural = '카테고리'


class Product(models.Model):
    name = models.CharField(verbose_name='상품명', max_length=256)
    price = models.IntegerField(verbose_name='상품가격')
    picture = models.ImageField(verbose_name='상품이미지', upload_to='product_img/',
                                default='product_img/no-image-icon.png')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(verbose_name='등록날짜',
                                         auto_now_add=True)
    is_discount = models.BooleanField(verbose_name='할인여부', default=False)
    discount_price = models.IntegerField(verbose_name='할인가격', blank=True,
                                         null=True)
    categories = models.ManyToManyField(
        verbose_name='카테고리',
        to=Category,
        related_name='%(app_label)s_%(class)s_related')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        verbose_name = '상품'
        verbose_name_plural = '상품'


class Review(models.Model):
    product = models.ForeignKey(verbose_name='상품', to=Product,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(verbose_name='고객', to=Customer,
                                 on_delete=models.CASCADE)
    rating = models.IntegerField(verbose_name='별점')
    contents = models.TextField(verbose_name='내용')

    def __str__(self):
        return '고객: ' + str(self.customer) + ' 상품: ' + str(
            self.product) + ' 별점: ' + str(
            self.rating) + ' 내용: ' + str(self.contents)

    class Meta:
        db_table = 'review'
        verbose_name = '상품평'
        verbose_name_plural = '상품평'

product/views.py
from rest_framework.generics import ListAPIView
from rest_framework.generics import RetrieveAPIView

from .pagination import ProductPagination
from .models import Review
from .models import Category
from .models import Product
from .serializer import CategorySerializer
from .serializer import ProductSerializer
from .serializer import ReviewSerializer


class ProductListAPI(ListAPIView):
    serializer_class = ProductSerializer
    pagination_class = ProductPagination

    def get_queryset(self):
        queryset = Product.objects.all().order_by('-pk')
        limit_count = self.request.query_params.get('limit_count', None)
        category = self.request.query_params.get('category', None)
        if limit_count:
            queryset = queryset[:int(limit_count)]
        if category:
            queryset = queryset.filter(categories=category)
        return queryset


class ProductDetailAPI(RetrieveAPIView):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('pk')


class CategoryListAPI(ListAPIView):
    serializer_class = CategorySerializer

    def get_queryset(self):
        return Category.objects.all().order_by('pk')


class ReviewListAPI(ListAPIView):
    serializer_class = ReviewSerializer

    def get_queryset(self):
        product = self.request.query_params.get('product-id', None)
        return Review.objects.filter(product=product)

templates/product/product-list.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="hero-wrap hero-bread"
     style="background-image: url({% static 'images/bg_6.jpg' %});">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs">
                    <span class="mr-2">Home</span>
                    <span>Shop</span>
                </p>
                <h1 class="mb-0 bread">Shop</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-10 order-md-last">
                <div class="row" id="product-table">
                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul id="pagination">

                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-lg-2">
                <div class="sidebar">
                    <div class="sidebar-box-2">
                        <h2 class="heading">
                            <a href="{% url 'product:list' %}">Categories</a></h2>
                        <div class="fancy-collapse-panel">
                            <div class="panel-group"
                                 id="accordion"
                                 role="tablist"
                                 aria-multiselectable="true">
                                <div class="panel-body">
                                    <ul id="category-table"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
<!--                    <div class="sidebar-box-2">-->
<!--                        <h2 class="heading">Price Range</h2>-->
<!--                        <form method="post" class="colorlib-form-2">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="form-group">-->
<!--                                        <label for="guests">Price from:</label>-->
<!--                                        <div class="form-field">-->
<!--                                            <i class="icon icon-arrow-down3"></i>-->
<!--                                            <select name="people" id="people" class="form-control">-->
<!--                                                <option value="#">1</option>-->
<!--                                                <option value="#">200</option>-->
<!--                                                <option value="#">300</option>-->
<!--                                                <option value="#">400</option>-->
<!--                                                <option value="#">1000</option>-->
<!--                                            </select>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="form-group">-->
<!--                                        <label for="guests">Price to:</label>-->
<!--                                        <div class="form-field">-->
<!--                                            <i class="icon icon-arrow-down3"></i>-->
<!--                                            <select name="people" id="people" class="form-control">-->
<!--                                                <option value="#">2000</option>-->
<!--                                                <option value="#">4000</option>-->
<!--                                                <option value="#">6000</option>-->
<!--                                                <option value="#">8000</option>-->
<!--                                                <option value="#">10000</option>-->
<!--                                            </select>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-gallery">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 heading-section text-center mb-4 ftco-animate">
                <h2 class="mb-4">Follow Us On Instagram</h2>
                <p>Far far away, behind the word mountains, far from the countries
                    Vokalia and Consonantia, there live the blind texts. Separated they
                    live in</p>
            </div>
        </div>
    </div>
    <div class="container-fluid px-0">
        <div class="row no-gutters">
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-1.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-1.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-2.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-2.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-3.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-3.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-4.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-4.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-5.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-5.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{% static 'images/gallery-6.jpg' %}"
                   class="gallery image-popup img d-flex align-items-center"
                   style="background-image: url({% static 'images/gallery-6.jpg' %});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script src="{% static 'js/product.js' %}"></script>
{% endblock %}
{% block ready %}
send_data = {};
let target_url = "{% url 'product:list-api' %}";
send_data['category'] = "";
getProductData(target_url, 2);
target_url = "{% url 'product:category-api' %}"
getCategoryData(target_url);
{% endblock %}