config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('order/', include('order.urls', namespace='order')),
    path('product/', include('product.urls', namespace='product')),
    path('obtain-token/', obtain_jwt_token, name='obtain-token'),
    path('refresh-token/', refresh_jwt_token, name='refresh-token'),
    path('verify-token/', verify_jwt_token, name='verify-token'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PaymentComplete
from .views import CartExistCheckAPI
from .views import OrderListAPI
from .views import CartListAPI

app_name = 'order'
urlpatterns = [
    path('', TemplateView.as_view(template_name='order/order.html'),
         name='order-list'),
    path('cart/', TemplateView.as_view(template_name='order/cart.html'),
         name='cart'),
    path('cart-api/', CartListAPI.as_view(), name='cart-api'),
    path('order-api/', OrderListAPI.as_view(), name='order-api'),
    path('exist-api/', CartExistCheckAPI.as_view(), name='exist-api'),
    path('payments-complete/', PaymentComplete.as_view(),
         name='payments-complete'),
]

product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CategoryListAPI
from .views import ProductListAPI
from .views import ProductDetailAPI

app_name = 'product'
urlpatterns = [
    path('', TemplateView.as_view(template_name='product/product-list.html'),
         name='list'),
    path('<int:pk>/',
         TemplateView.as_view(template_name='product/product-detail.html'),
         name='detail'),
    path('list-api/', ProductListAPI.as_view(), name='list-api'),
    path('detail-api/<int:pk>/', ProductDetailAPI.as_view(),
         name='detail-api'),
    path('category-list-api/', CategoryListAPI.as_view(), name='category-api'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800"
          rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet"
          href="{% static '/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/animate.css' %}">

    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static '/css/aos.css' %}">

    <link rel="stylesheet" href="{% static '/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static '/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static '/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static '/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static '/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body class="goto-here">
<div class="py-1 bg-black">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-phone2"></span>
                        </div>
                        <span class="text">+82 123 4567 8901</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-paper-plane"></span>
                        </div>
                        <span class="text">admin@admin.com</span>
                    </div>
                    <div id="show-nickname" class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light"
     id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">OnlineShop</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#ftco-nav"
                aria-controls="ftco-nav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'home' %}" class="nav-link">Home</a>
                </li>
                <li id="login" class="nav-item">

                </li>
                <li class="nav-item">
                    <a href="{% url 'product:list' %}" class="nav-link">Shop</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'order:cart' %}" class="nav-link">Cart</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'order:order-list' %}" class="nav-link">Order</a>
                </li>
                <li class="nav-item cta cta-colored">
                    <a href="{% url 'order:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Minishop</h2>
                    <p>Far far away, behind the word mountains, far from the countries
                        Vokalia and Consonantia.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'product:list' %}" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
                            <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a>
                            </li>
                            <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a>
                            </li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li>
                                <a href="#"><span class="icon icon-phone"></span><span
                                        class="text">+81 123 4567 8901</span></a>
                            </li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span
                                    class="text">admin@admin.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with
                    <i class="icon-heart color-danger" aria-hidden="true"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg"
                cx="24"
                cy="24"
                r="22"
                fill="none"
                stroke-width="4"
                stroke="#eeeeee"/>
        <circle class="path"
                cx="24"
                cy="24"
                r="22"
                fill="none"
                stroke-width="4"
                stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/jwt-decode.min.js' %}"></script>
<script src="{% static 'js/customer-auth.js' %}"></script>

{% block script %}
{% endblock %}
<script>
$(document).ready(function () {
    renderLoginStatus();
{% block ready %}
{% endblock %}
});
</script>
</body>
</html>